#!/bin/bash

FORGEBUILD="`dirname \"$0\"`" # Relative
export FORGEBUILD="`( cd \"$FORGEBUILD\" && pwd )`" # Absolutized and normalized
pushd $FORGEBUILD

shopt -s nullglob
for f in * ; do sudo rm -f "./$f" ; done
