#!/bin/bash

FORGEBUILD="`dirname \"$0\"`" # Relative
export FORGEBUILD="`( cd \"$FORGEBUILD\" && pwd )`" # Absolutized and normalized
pushd $FORGEBUILD

for f in */; do rm -Rf "$f"; done
for f in *; do
	if [ "$f" != "cleanup" ]; then
		rm -f "./$f"
	fi
done
